name: pip_flutter
description: A new Flutter Picture in Picture Package for android.When app is
  running in foregorund that time also app not kill.
version: 0.0.4
homepage: https://github.com/kesmitopiwala/pip_flutter/blob/master/example/lib/main.dart

environment:
  flutter: "3.13.2"
  sdk: ">=3.1.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  wakelock_plus: ^1.2.8
  visibility_detector: ^0.4.0+2
  xml: ^6.2.2
  flutter_widget_from_html_core: ^0.15.2
  path_provider: ^2.0.5
  

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.pip_flutter
        pluginClass: PipFlutterPlugin
      ios:
        pluginClass: PipFlutterPlugin
